tunnel: 49f98be7-61f0-4364-b076-f34bba5cccd7
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: dockerstackds2api.dpdns.org
    service: http://caddy:80
  - hostname: main.dockerstackds2api.dpdns.org
    service: http://caddy:80
  - hostname: ttyd.dockerstackds2api.dpdns.org
    service: http://caddy:80
  - hostname: dozzle.dockerstackds2api.dpdns.org
    service: http://caddy:80
  - hostname: files.dockerstackds2api.dpdns.org
    service: http://caddy:80
  - hostname: deploy.dockerstackds2api.dpdns.org
    service: http://caddy:80
  - service: http_status:404
